version: '3.3'
services:
  flug-checker:
    build: .
    ports:
      - 7474:8000
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=flug-mongodb
     - MONGO_PORT=27022
     - MONGO_USER=enoislove
     - MONGO_PASSWORD=enoislife
  mongodb:
    image: mongo
